# Generated by Django 4.2.4 on 2023-08-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofquestions',
            name='ans',
            field=models.TextField(null=True),
        ),
    ]
